# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# https://developer.android.com/studio/command-line for more details.
# When configured, Gradle will ignore 'bundleReleaseResources' task in all multi-library projects.
# android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
